name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: npm install
  
      - name: Build Angular App
        run: npm run build

      - name: Build the Angular app
        run: npm run build -- --configuration=production

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/crisionas.github.io
        env:
          CI: true
          GH_TOKEN: ${{ secrets.TOKEN }}
